"$schema" = 'https://starship.rs/config-schema.json'

# --- HLAVNÍ FORMÁT ---
format = """
[╭─](fg:overlay0)\
$username\
[](bg:sapphire fg:red)\
$os\
$hostname\
[](bg:peach fg:sapphire)\
$directory\
${custom.dir_end_no_git}\
$git_branch\
$git_metrics\
${custom.git_end}\
$fill\
$cmd_duration\
$fill\
$status\
[](fg:lavender bg:surface0)\
$time\
$line_break\
[╰─](fg:overlay0)\
$character"""

palette = 'catppuccin_mocha'

# --- MODULY LEVÁ STRANA ---

[username]
show_always = true
style_user = "bg:red fg:crust"
style_root = "bg:red fg:crust bold"
format = '[  $user ]($style)'

[os]
disabled = false
style = "bg:sapphire fg:crust"
format = '[ $symbol]($style)'

[hostname]
ssh_only = false
style = "bg:sapphire fg:crust"
format = '[ $hostname ]($style)'

[directory]
style = "bg:peach fg:crust"
format = "[   $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# --- GIT SEKCE ---
[git_branch]
symbol = ""
style = "bg:green fg:crust"
format = '[](fg:peach bg:green)[ $symbol $branch ]($style)'

[git_metrics]
disabled = false
added_style = "bold bg:green fg:crust"
deleted_style = "bold bg:green fg:crust"
format = '[+$added]($added_style)[-$deleted]($deleted_style)'

# --- VÝPLŇ ---
[fill]
symbol = "─"
style = "fg:overlay0"

# --- MODULY PRAVÁ STRANA ---

[time]
disabled = false
time_format = "%R"
style = "bg:lavender fg:crust"
# Formát času (napojuje se na status)
format = '[   $time ]($style)'

[cmd_duration]
min_time = 2000
format = "[](fg:surface1)[  $duration ](bg:surface1 fg:white)[](fg:surface1)"

# --- OSTATNÍ ---

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[ ❯](bold green)'
error_symbol = '[ ❯](bold red)'

[custom.dir_end_no_git]
command = "echo -n"
when = '! git rev-parse --is-inside-work-tree 2> /dev/null'
format = "[](fg:peach)"

[custom.git_end]
command = "echo -n"
when = 'git rev-parse --is-inside-work-tree 2> /dev/null'
format = "[](fg:green)"


# --- IKONY A BARVY ---
[os.symbols]
Windows = ""
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
